"""init

Revision ID: 0d4a458e48a9
Revises: 
Create Date: 2025-04-16 18:46:58.304934

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0d4a458e48a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='user_role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_title'), 'lesson', ['title'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_id'), 'recommendation', ['id'], unique=False)
    op.create_table('test',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_id'), 'test', ['id'], unique=False)
    op.create_index(op.f('ix_test_title'), 'test', ['title'], unique=False)
    op.create_table('assignment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_id'), 'assignment', ['id'], unique=False)
    op.create_index(op.f('ix_assignment_title'), 'assignment', ['title'], unique=False)
    op.create_table('testresult',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testresult_id'), 'testresult', ['id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('assignment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_testresult_id'), table_name='testresult')
    op.drop_table('testresult')
    op.drop_index(op.f('ix_assignment_title'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_test_title'), table_name='test')
    op.drop_index(op.f('ix_test_id'), table_name='test')
    op.drop_table('test')
    op.drop_index(op.f('ix_recommendation_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_lesson_title'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
