"""create chat_messages table

Revision ID: 21d0fdbc13b1
Revises: cadb83bd3945
Create Date: 2025-04-16 19:41:07.011263

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '21d0fdbc13b1'
down_revision = 'cadb83bd3945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
