"""add user-course many-to-many

Revision ID: 22a19c638c8d
Revises: b5339315ef1a
Create Date: 2025-04-16 19:22:55.251961

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '22a19c638c8d'
down_revision = 'b5339315ef1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_association',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='user_course_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_course_user_id_fkey')
    )
    op.drop_table('user_course_association')
    # ### end Alembic commands ###
