"""add user-course many-to-many

Revision ID: cadb83bd3945
Revises: 22a19c638c8d
Create Date: 2025-04-16 19:32:11.809812

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cadb83bd3945'
down_revision = '22a19c638c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('lesson', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('lesson', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('lesson', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'video_url')
    op.drop_column('lesson', 'is_published')
    op.drop_column('lesson', 'duration_minutes')
    op.drop_column('lesson', 'order')
    # ### end Alembic commands ###
